spring:
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:postgresql://localhost:5432/learning
    username: postgres
    password: imu123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
allowed:
  origins: https://localhost:3000
#okta:
#  oauth2:
#    client-id: 0oa8kdtyptf2ORBJB5d7
#    client-secret: oZTL3jmiPEHMuEXyWOKYZpO0TcQSX9sePD4BT2qk
#    issuer: https://dev-62048629.okta.com/oauth2/default
#server:
#  port: 8443
#  ssl:
#    enabled: true
#    key-alias: luv2code
#    key-store: classpath:luv2code-keystore.p12
#    key-store-password: secret
#    key-store-type: PKCS12